FROM openjdk:11
EXPOSE 8081
ADD target/airlinereservationsystem-0.0.1-SNAPSHOT.jar airlinereservationsystem-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","/airlinereservationsystem-0.0.1-SNAPSHOT.jar" ]